# 1.Print 'Hello HCIA'.

In [1]:
print ('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [3]:
a = 10
b = 15
c = a+b
print(c)

25


# 3.Define a list and replicate in three different ways.

In [7]:
a = [1,2,3]
print(a)
print(a*2)
print(a*3)

[1, 2, 3]
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


# 4.Define two lists and merge them together.

In [8]:
a = [1,2,3]
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


# 5. Get the last element of the list and print it.

In [12]:
a = [1,2,3,4,5]
print(a[-1])

5


# 6.Define a tuple that contains only one element.

In [13]:
tup = ('odin')

# 7.Define a three-line long string.

In [59]:
string = ("""one
two
three""")


one
two
three


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [19]:
tup = (1,2,3)
b = enumerate(tup)
for i in b:
    print(i)

(0, 1)
(1, 2)
(2, 3)


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [24]:
def funct(x, y):
    return(x*y)
funct(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [36]:
import numpy as np
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [38]:
import numpy as np
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [56]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [63]:
import numpy as np
a = np.arange(4).reshape(2,2)
b = np.matrix('0,1; 2,3')
c = numpy.multiply(a,b)
print(c)

[[0 1]
 [4 9]]
